spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:h2:mem:customer-db
  cloud:

    service-registry:
      auto-registration:
        enabled: false
    config:
      enabled: false
      discovery:
        enabled: false

eureka:
  client:
    enabled: false






server:
  port: 8056




